#ifndef _RAM_h
#define _RAM_h

//defines
typedef unsigned char RAM;

//defines for ram locations
#define RAM_LOCATION_ROM_0_START 0x0000
#define RAM_LOCATION_ROM_0_END 0x3FFF
#define RAM_LOCATION_ROM_SWAPPABLE_START 0x4000
#define RAM_LOCATION_ROM_SWAPPABLE_END 0x7FFF
#define RAM_LOCATION_VIDEO_START 0x8000
#define RAM_LOCATION_VIDEO_END 0x9FFF
#define RAM_LOCATION_RAM_SWAPPABLE_START 0xA000
#define RAM_LOCATION_RAM_SWAPPABLE_END 0xBFFF
#define RAM_LOCATION_RAM_INTERNAL_1_START 0xC000
#define RAM_LOCATION_RAM_INTERNAL_1_END 0xDFFF
#define RAM_LOCATION_RAM_ECHO_START 0xE000
#define RAM_LOCATION_RAM_ECHO_END 0xFDFF
#define RAM_LOCATION_OAM_START 0xFE00
#define RAM_LOCATION_OAM_END 0xFE9F
#define RAM_LOCATION_UNUSABLE_1_START 0xFEA0
#define RAM_LOCATION_UNUSABLE_1_END 0xFEFF
#define RAM_LOCATION_IO_START 0xFF00
#define RAM_LOCATION_IO_END 0xFF4B
#define RAM_LOCATION_UNUSABLE_2_START 0xFF4C
#define RAM_LOCATION_UNUSABLE_2_END 0xFF7F
#define RAM_LOCATION_RAM_INTERNAL_2_START 0xFF80
#define RAM_LOCATION_RAM_INTERNAL_2_END 0xFFFE
#define RAM_LOCATION_INTERRUPT_ENABLE 0xFFFF

//function prototypes
//initialize RAM
RAM* RAM_init(void);

//dispose of the ram stack
void RAM_dispose(RAM* RAM_ptr);
#endif // !RAM
